# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: gpu-pool

container:
  image: nvcr.io/nvidia/pytorch:21.06-py3
  options: --gpus all
  #image: pytorch/pytorch:1.9.1-cuda11.1-cudnn8-devel
  #options: --gpus all --shm-size 8G

steps:

- bash: |
    ls -l /usr/local | grep cuda
    /usr/local/cuda/bin/nvcc --version
    nvcc --version
    whereis nvidia
    nvidia-smi
    python --version
    pip --version
    pip list
  displayName: 'Image info & NVIDIA'

- script: |
    python -m pip install --upgrade pip
    pip install .[all]
  displayName: 'Install dependencies'

- script: |
    pytest -v --device cuda --dtype float32,float64 ./test
  displayName: 'pytest'
